### ISSUE TITLE
 issues

### ISSUE THREAD

**Issue by SHYang1210** [choicelab/grasping-invisible#3]
Hi, hello, I am very interested in your work. I am running your main.py on the 2070 GPU. For time issues, how long will it take to stop itself?

**Comment by SHYang1210** [comment]
When I test, the following problems will appear.
My command is: python main.py --is_testing --test_preset_cases --test_target_seeking
-----------------------
Creating data logging session: / home / vulcan / grasping-invisible-master / logs / testing / release / random-3blocks
Connected to simulation.
Traceback (most recent call last):
   File "main.py", line 546, in <module>
     main (args)
   File "main.py", line 70, in main
     robot = Robot (workspace_limits, is_testing, test_preset_cases, config_file)
   File "/home/vulcan/grasping-invisible-master/robot.py", line 58, in __init__
     self.sim_read_config_file (config_file)
   File "/home/vulcan/grasping-invisible-master/robot.py", line 85, in sim_read_config_file
     self.obj_mesh_files.append (line_content [1])
IndexError: list index out of range

But, there are no tesing files and sub-files in the automatically generated logs file.
Looking forward to your help, thank you.

**Comment by SHYang1210** [comment]
When I test, the following problems will appear.
My command is: python main.py --is_testing --test_preset_cases --test_target_seeking --config_file / home / vulcan / grasping-invisible-master / simulation / preset
-----------------------
Creating data logging session: / home / vulcan / grasping-invisible-master / logs / testing / release / preset
Connected to simulation.
Traceback (most recent call last):
   File "main.py", line 546, in <module>
     main (args)
   File "main.py", line 70, in main
     robot = Robot (workspace_limits, is_testing, test_preset_cases, config_file)
   File "/home/vulcan/grasping-invisible-master/robot.py", line 58, in __init__
     self.sim_read_config_file (config_file)
   File "/home/vulcan/grasping-invisible-master/robot.py", line 66, in sim_read_config_file
     raise Exception ('config file not exist')
Exception: config file not exist

However, there are no tesing files and sub-files in the automatically generated logs file.
Looking forward to your help, thank you.

**Comment by SHYang1210** [comment]
I stopped the program after training more than 5,000 times, and then evaluated it. The result is as follows: Success rate 46.5
Mean number of motions 16.80, std 4.19
I found that the success rate is too different from your results. I do n’t know what caused it, which caused inconvenience to you, thank you.
